universe = vanilla
log = log_$(Cluster).log
output = output_$(Cluster)_$(Process).out
error = error_$(Cluster)_$(Process).err

executable = run_extraction.sh
arguments = $(config)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_gpus = 1
request_cpus = 1
request_memory = 10GB
request_disk = 30GB

+WantGPULab = true
+GPUJobLength = "short"
require_gpus = (DriverVersion >= 10.2) && (Capability < 8)

queue config from cmd.txt