universe = vanilla
log = log_$(Cluster).log

executable = run_extraction.sh
arguments = $(config)
output = output_$(Cluster)_$(Process).out
error = error_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = feature_extraction.tar.gz, code.tar.gz

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

# Tell HTCondor to run 3 instances of our job:
queue config from cmd.txt