io:
  filter_completed: true
  video_dir_path: /home/alex/workspace/video_feature_extraction/videos
  ego4d_download_dir: inputs
  uid_list: null
  video_limit: -1
  out_path: /home/alex/workspace/video_feature_extraction/results
  debug_path: debug
  debug_mode: false
  exclude_no_audio: false
inference_config:
  device: cuda
  batch_size: 32
  num_workers: 4
  prefetch_factor: 2
  fps: 30 
  frame_window: 16
  stride: 4
  include_audio: false
  include_video: true
  norm_config:
    normalize_audio: false
    resample_audio_rate: 16000
    resampling_method: "sinc_interpolation"
schedule_config:
  run_locally: true
  log_folder: slurm_log/%j
  timeout_min: 3200
  constraint: volta
  slurm_partition: pixar
  slurm_array_parallelism: 128
  gpus_per_node: 1
  cpus_per_task: 10
  overhead: 1.1
  time_per_forward_pass: 2.4
  schedule_time_per_node: 10.0
model_config:
  pretrained_dataset: sports1m
  side_size: 288
  crop_size: 112
  dilation: 1
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
  crop: five_crops
  mirror: true
model_module_str: models.c3d
