io:
  filter_completed: true
  video_dir_path:  /home/alex/workspace/video_feature_extraction/videos
  ego4d_download_dir: inputs
  uid_list: null
  video_limit: -1
  out_path: /home/alex/workspace/video_feature_extraction/results
  debug_path: debug
  debug_mode: false
  exclude_no_audio: false
inference_config:
  device: cuda
  batch_size: 32
  num_workers: 0
  prefetch_factor: 2
  frame_window: 6
  stride: 6
  include_audio: false
  include_video: true
  norm_config:
    normalize_audio: false
    resample_audio_rate: 16000
    resampling_method: "sinc_interpolation"
schedule_config:
  run_locally: true
  log_folder: slurm_log/%j
  timeout_min: 3200
  constraint: volta
  slurm_partition: pixar
  slurm_array_parallelism: 128
  gpus_per_node: 1
  cpus_per_task: 10
  overhead: 1.1
  time_per_forward_pass: 2.4
  schedule_time_per_node: 10.0
model_config:
  use_remote: true
  hub_path: ViT-B-32
  model_name: "clip"
  input_type: "video"
  side_size: 224
  crop_size: 224
  dilation: 1
  mean:
  - 0.48145466
  - 0.4578275
  - 0.40821073
  std:
  - 0.26862954
  - 0.26130258
  - 0.27577711
  crop: center
  mirror: true

model_module_str: models.clip
